export const WEBRING_MEMBERS = {
    "sites": [
        {
            "name": "Daniel Palma",
            "year": "2026",
            "website": "https://dpalma.dev",
            "role": "Head of Finance",
        },
        {
            "name": "Lewin Bobda",
            "year": "2026",
            "website": "https://lewinbobda.com",
            "role": "Co-Founder",
        },
        {
            "name":"Alex Palma",
            "year": "2026",
            "website": "https://alexpalma.dev",
            "role": "Office Manager",
        },
        {
            "name": "Michał Dziubek",
            "year": "2026",
            "website": "https://michaldziubek.com",
            "role": "Software Engineer",
        },
        {
            "name": "Liam McKenzie",
            "year": "2026",
            "website": "https://liam.mckenzie.dev",
            "role": "Audio Engineer",
        },
        {
            "name": "Sofia Zhang",
            "year": "2025",
            "website": "https://sofiazhang.dev",
            "role": "UX Designer",
        },
        {
            "name": "Arjun Patel",
            "year": "2024",
            "website": "https://arjunpatel.dev",
            "role": "Frontend Developer",
        },
        {
            "name": "Isabella Gomez",
            "year": "2026",
            "website": "https://isabellagomez.dev",
            "role": "Product Manager",
        },
        {
            "name": "Noah Smith",
            "year": "2025",
            "website": "https://noahsmith.dev",
            "role": "Cloud Engineer",
        },
        {
            "name": "Emily Nguyen",
            "year": "2026",
            "website": "https://emilynguyen.dev",
            "role": "Security Analyst",
        },
        {
            "name": "Omar El-Sayed",
            "year": "2026",
            "website": "https://omares.dev",
            "role": "Systems Architect",
        },
        {
            "name": "Grace Lee",
            "year": "2025",
            "website": "https://gracelee.dev",
            "role": "Content Strategist",
        },
        {
            "name": "Lucas Martin Johnson",
            "year": "2024",
            "website": "https://lucasjohnson.dev",
            "role": "Mobile Developer",
        },
        {
            "name": "Harper Davies",
            "year": "2025",
            "website": "https://harperdavies.dev",
            "role": "AI Researcher",
        },
        {
            "name": "Mateo Rivera",
            "year": "2026",
            "website": "https://mateorivera.dev",
            "role": "Backend Engineer",
        },
        {
            "name": "Chloe Martin",
            "year": "2026",
            "website": "https://chloemartin.dev",
            "role": "QA Engineer",
        },
        {
            "name": "Ethan Wright",
            "year": "2024",
            "website": "https://ethanwright.dev",
            "role": "Data Scientist",
        },
        {
            "name": "Ava Thompson",
            "year": "2025",
            "website": "https://avathompson.dev",
            "role": "Operations Analyst",
        },
        {
            "name": "Zane Kim",
            "year": "2026",
            "website": "https://zanekim.dev",
            "role": "DevOps Engineer",
        },
        {
            "name": "Maya Fernandez",
            "year": "2026",
            "website": "https://mayafernandez.dev",
            "role": "Business Analyst",
        },
        {
            "name": "Caleb Brooks",
            "year": "2025",
            "website": "https://calebbrooks.dev",
            "role": "Database Administrator",
        },
        {
            "name": "Leila Hassan",
            "year": "2026",
            "website": "https://leilahassan.dev",
            "role": "Design Lead",
        },
        {
            "name": "Benjamin Clark",
            "year": "2026",
            "website": "https://benjaminclark.dev",
            "role": "Tech Lead",
        },
        {
            "name": "Nina Popov",
            "year": "2025",
            "website": "https://ninapopov.dev",
            "role": "UI Developer",
        },
        {
            "name": "Derek Allen",
            "year": "2024",
            "website": "https://derekallen.dev",
            "role": "Hardware Engineer",
        },
        {
            "name": "Yara Al-Karim",
            "year": "2026",
            "website": "https://yaraalkarim.dev",
            "role": "Program Manager",
        },
        {
            "name": "Julian Torres",
            "year": "2026",
            "website": "https://juliantorres.dev",
            "role": "Research Assistant",
        },
        {
            "name": "Freya Singh",
            "year": "2025",
            "website": "https://freyasingh.dev",
            "role": "Technical Writer",
        },
        {
            "name": "Leo Schneider",
            "year": "2026",
            "website": "https://leoschneider.dev",
            "role": "Infrastructure Engineer",
        },
        {
            "name": "Zoey Bennett",
            "year": "2024",
            "website": "https://zoeybennett.dev",
            "role": "Recruiter",
        },
        {
            "name": "Henry Dubois",
            "year": "2026",
            "website": "https://henrydubois.dev",
            "role": "Software Tester",
        },
        {
            "name": "Alina Petrov",
            "year": "2025",
            "website": "https://alinapetrov.dev",
            "role": "Technical Recruiter",
        },
                {
            "name": "Leo Schneider",
            "year": "2026",
            "website": "https://leoschneider.dev",
            "role": "Infrastructure Engineer",
        },
        {
            "name": "Zoey Bennett",
            "year": "2024",
            "website": "https://zoeybennett.dev",
            "role": "Recruiter",
        },
        {
            "name": "Henry Dubois",
            "year": "2026",
            "website": "https://henrydubois.dev",
            "role": "Software Tester",
        },
        {
            "name": "Alina Petrov",
            "year": "2025",
            "website": "https://alinapetrov.dev",
            "role": "Technical Recruiter",
        },
    ]
} as const;
